### ISSUE TITLE
chain list

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/notional#2]
- [x] sentinel 
- [ ] v-systems
- [x] osmosis xxx
- [x] regen
- [x] desmos  
- [ ] stakebird
- [x] sif xxx
- [x] luna
- [x] juno
- [ ] turbogeth or whatever
- [ ] binance chain (BSC)
- [ ] blurt xxx
- [ ] Peercoin
- [x] iov 
- [x] kava
- [x] akash
- [x] gaia
- [x] crypto.org
- [x] anon
- [x] beach
- [x] chain-main
- [x] dig
- [x] omniflux
- [x] persistance core
- [x] starname

right, so lets see how many have been done.
Oh, Minh is testing on server and PI.

comment below if I am missing anything.

**Comment by MasterPi-2124** [comment]
where did you get that?

**Comment by nghuyenthevinh2000** [comment]
Khanh compiles a list

**Comment by MasterPi-2124** [comment]
how to check an item?

**Comment by faddat** [comment]
This is great.

**Comment by MasterPi-2124** [comment]
Update:
- **Gaia**: work
- **Osmosis**: failed
> ```
> panic: failed to execute message; message index: 0: cannot set validator commission to less than minimum rate of 0.050000000000000000: commission cannot be less than min rate
> ```
- **Akash**: work
- **Sentinel**: failed
> ```
> Error: error reading GenesisDoc at /root/.sentinelhub/config/genesis.json: invalid character '<' looking for beginning of value
> ```
- **Starnamed**: failed
> ```
> Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
> ```
- **Regen**: failed
> ```
> Error: set min gas price in app.toml or flag or env variable: error in app.toml
> ```
- **Juno**: failed
> ```
> Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
> ```
- **Sifnode**: failed
> ```
> Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
> ```
- **OmniFlixhub**: failed
> ```
> Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
> ```
