### ISSUE TITLE
Relayer

### ISSUE THREAD

**Issue by MasterPi-2124** [notional-labs/notional#21]
Running Nodes
- relay1
- [x] Crypto
- [x] Microtick
- [x] Persistence
- [x] Injective
- [x] Likecoin
- [x] Bitcana
- [x] Terra
- relay2
- [x] Sifnode
- [x] Ixo
- [x] Starname
- [x] Akash
- [x] Osmosis
- [x] Iris
- [x] Gaia
- [x] Juno
- [x] E-money
- [x] Regen
- [x] Sentinel

**Comment by MasterPi-2124** [comment]
oh I think it is not published so I just make my own checklist. Thank you for your suggestion.

**Comment by faddat** [comment]
Please continue to work on it in public :)

**Comment by faddat** [comment]
so great, thank you
