### ISSUE TITLE
Incident Report #2: Gaia takes too much usage on Pi

### ISSUE THREAD

**Issue by MasterPi-2124** [notional-labs/notional#23]
# Description
### Time and Location
- Time: 16:00 - 17:00 ICT 10/14/21
- Location: Raspberry Pi 4GB
### Detail
Gaia missed some blocks and take too much RAM usage. The Pi became unresponding after a while.
# Cause
*Detail cause will appear here*
# Solution
We tried to replace the Pi with Raspberry Pi 8GB, and currently tracking for performance.

**Comment by faddat** [comment]
resolved
