### ISSUE TITLE
Incident Report #5: Injective is so vulnerable

### ISSUE THREAD

**Issue by MasterPi-2124** [notional-labs/notional#27]
# Description
### Time and Location
- Time: 12:00  ICT 10/19/21
- Location: Server running Hermes relayer.
### Detail
Injective keep crashing with panic errors.
```
panic: Failed to process committed block (2045753:A63C57B2649076F59838F628BC17924470144FE3B07FB4CAFE21D502D20B9F31): wrong Block.Header.AppHash.  Expected A46CCBDCE9A5540A9A1FCA02718532A81CEC0071E6D58109F03A2E5D35423201, got CFE969288E344C6C9EAD071561A5C6A033D098CADF43B4317521AA421C00D10B
```
# Cause
At first, I decided it was a version error, and try many other versions, but all of them didn't work either. For now, injective is running version [`Mainnet-10001-rc5-1627871816`](https://github.com/InjectiveLabs/injective-chain-releases/releases/tag/v1.0.1-1627871816).
# Solution
Till now, there have been no solutions yet.

**Comment by faddat** [comment]
These reports should go in the incident reports folder please and then also possibly create an issue on their repository and thank you
