### ISSUE TITLE
Hieu and Chinh's onboarding

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/notional#45]
- [x] add to slack
- [x] add to github of Notional
- [x] add to telegram of Notional
- [x] introduce to various projects in process
- [x] assign tasks

**Comment by nghuyenthevinh2000** [comment]
Hieu: +84 836184548
Chinh: +84 348818282 | @nguyenchinh1803

**Comment by nghuyenthevinh2000** [comment]
task assigned: https://github.com/notional-labs/anone/issues/6

**Comment by mgialong215** [comment]
we should not public their personal numbers

**Comment by mgialong215** [comment]
I made it hidden
