### ISSUE TITLE
Authz  research

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/notional#56]
# I. Task description
In the word of @thecryptodrive 

> I have a pain point I would love help with, so my main tasks are payroll, gov and claims, first two are fine, Claims really gets me down, i fight with three explorers, ping, lookchill and the skyexplorer one, I haven't been able to claim osmo val rewards, only the staking and pool rewards as the api has issues, same with other chains, some work some don't so like I land up disliking the work and don't do it as well as I should because it is so fiddly and buggy, if we can get validators that support onto Authz would be really nice so i can focus on commercials instead of feeling frustrated with claims.

# II. Task timeline
Specify timeline if exists

# III. Task goals 
goals that this task needs to achieve

- [x]  Investigate whether Authz can solve the above problem: https://docs.cosmos.network/master/modules/authz/
- [ ] create a tool for auto - restake and auto - claim

**Comment by nghuyenthevinh2000** [comment]
1. https://github.com/cosmos/cosmos-sdk/blob/main/x/authz/client/cli/tx.go#L96

**Comment by nghuyenthevinh2000** [comment]
plan:
1. Ricardo will authorize developer address for two actions: claim and stake. There will be a fast script for this.
2. Tool will automatically re - stake and claim everyday.
3. Tool will automatically write down profit to an excel file everyday.
4. There will be an option to exclude re - stake for specific validators in case we need money.

**Comment by mgialong215** [comment]
https://github.com/eco-stake/restake
