### ISSUE TITLE
Spark IBC research

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/notional#57]
# I. Task description
Research:
1. this whitepaper: https://t.co/ZgPQsxB2ym
2. how to create a dao

# II. Task timeline
deadline: 08/05

# III. Task goals 
goals that this task needs to achieve

- [ ]  basic understand of whitepaper
- [ ] basic understand of how a dao works

**Comment by chinhnotional** [comment]
[Spark IBC.odt](https://github.com/notional-labs/notional/files/8646157/Spark.IBC.odt)

**Comment by chinhnotional** [comment]
[How a DAO work.odt](https://github.com/notional-labs/notional/files/8646376/How.a.DAO.work.odt)

**Comment by chinhnotional** [comment]
Ok, i have noted my knowledge about Spark IBC whitepaper and how a DAO work in these above files. Pls check them. @nghuyenthevinh2000

**Comment by chinhnotional** [comment]
[Spark-IBC.pdf](https://github.com/notional-labs/notional/files/8646885/Spark-IBC.pdf)
[How-a-DAO-work.pdf](https://github.com/notional-labs/notional/files/8646886/How-a-DAO-work.pdf)

**Comment by nghuyenthevinh2000** [comment]
https://trello.com/b/ng6f1OWS/roadmap

**Comment by nghuyenthevinh2000** [comment]
#59 
no funding

**Comment by TendermintTimmy** [comment]
Apologies on any time wasted here! We'll certainly be in touch in the future. Thanks again
