### ISSUE TITLE
Weekly Self-report

### ISSUE THREAD

**Issue by ThanhNhann** [notional-labs/notional#69]
### Who is writing this?

ThanhNhann

### Valid start of this week

28/06/2022

### Brief summary of what you are doing

# What I am doing 1:  Make all incentive keeper gauge tests table driven
* Link to issues, pr?
    https://github.com/osmosis-labs/osmosis/issues/476  
* Any problems doing this?
   - I had code test cases but faced this bug, I also checked the root of the bug (from the error trace) with Khanh but right now it is still there
   
    ![Screenshot from 2022-07-04 22-16-21](https://user-images.githubusercontent.com/28915032/177182422-a1637661-f6f2-4fc6-bd2c-ebfc5e5935ae.png)
     -  The bug appears when there is more than one line of code `SetupManyLocks` in test cases:
     
            suite.SetupManyLocks(5, defaultLiquidTokens, defaultLPTokens, time.Second)
* How many hours doing this?
    - About 10 hours
# What I am doing 2:  Reading dig source code and doc of osmosis + learn about cosmos - sdk
* Link to issues, pr?
* Any problems doing this?
  -  None (until now)
* How many hours doing this?
  -  About 8 hours

**Comment by nghuyenthevinh2000** [comment]
has the bug been fixed?
