### ISSUE TITLE
can we run nodes using state sync

### ISSUE THREAD

**Issue by romelukaku** [notional-labs/notional#9]
seems like 8TB is a little bit too much

**Comment by faddat** [comment]
gaia and osmo can state sync for sure.  

make a script that loads the needed config into environment variables.  

(trust height and trust hash)

(node one and node two)

our nodes are at https://github.com/osmosis-labs/awesome

**Comment by faddat** [comment]
I figure that the big question is more like:

"Can we state sync in Akash, so that we can sign blocks with Horcrux from scattered raspberry Pi's"?

**Comment by faddat** [comment]
Answer:  Yes, we have a state synced gaia that runs happy on an rpi.  

Longer answer:  Seems to me that state sync is currently not suited to the relay nodes, but well-suited to validator nodes.  For now we need to think about three kinds of nodes for the ipfs system:

* Default
* Pruned
* Archive
